name: academy_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.4
  flutter_svg: ^0.15.0
  shared_preferences: ^0.5.6
  provider: ^4.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/images/department/
  - assets/images/imgList/


  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
    - family: AvenirBold
      fonts:
        - asset: assets/fonts/AvenirBold.otf
    - family: SultanNahia
      fonts:
        - asset: assets/fonts/SultanNahia.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf

